# Generated by Django 5.2.1 on 2025-05-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('control', models.CharField(max_length=50, verbose_name='Control U')),
                ('licencia', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10)),
            ],
        ),
    ]
