# Generated by Django 5.2.1 on 2025-05-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('telefono', models.CharField(help_text='Usado como ID único', max_length=20, primary_key=True, serialize=False, verbose_name='Teléfono')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
    ]
